### PR TITLE
Dataset-migration

### PR DESCRIPTION
**Pull request by marfcg**

### CODE REVIEW

**Comment by xmnlab** [comment]
@marfcg 

great!

**Comment by xmnlab** [comment]
@marfcg 

> 'Unidade da Federação': 'state_country_name', # Not needed in the table

Ok I will remove the column from dataframe :+1:

**Comment by xmnlab** [comment]
@marfcg 

The territory type field (Tipo) could be removed from the tables and added in a Territory table ... I will do it in the notebook

**Comment by marfcg** [comment]
>The territory type field (Tipo) could be removed from the tables and added in a Territory table ... I will do it in the notebook

Yep.

**Comment by xmnlab** [comment]
new version: https://github.com/xmnlab/fludashboard/blob/development/Notebooks/Dataset-Migration.ipynb

**Pull request merged**
